README.md
action.yml
entrypoint.sh

This change, while a breaking change, will allow for the usage in
non-ponylang projects.
Closes #1

Don't tie release commits to ponylang-main account

---

scripts/announce-a-release.bash

When I added support for adding release notes from the release-notes-bot,
it was intended to be optional. However, because the rotation of the
new-release.md file wasn't wrapped in a check to see if it exists,
then using 0.2.1 without .release-notes/new-release.md would error out.
After this commit, release-notes-bot support is now actually optional.

Make .release-notes support optional

---

README.md
scripts/announce-a-release.bash

Previously, you had to provide an ASSET_NAME env variable to the
announcement script. However, this was always the name of the repo.
With this change, we now use the repo name itself rather than
requiring a name to be given. This will change most things slightly
as the repo name contains the org.
Previously an asset name might be "corral" but would now be "ponylang/corral"
Closes #5

Make ASSET_NAME hardcoded

---

scripts/announce-a-release.bash

The empty line is always removed manually, and it would be slightly convenient not to have to do that.

Remove empty line in Last Week in Pony announcement

---

.github/workflows/release-notes-reminder.yml
.release-notes/23.md
README.md
scripts/trigger-release-announcement.bash

Prior to this commit, the trigger release announcement step
gets the version from GITHUB_REF. For this to work, the step
has to be triggered by a tag being pushed.
This is good for most use-cases, but not all. For example, ponyc
build assets for release on cirrus-ci not github actions. This
means that we want to trigger a release announcement once we've
been notified assets have been uploaded to cloudsmith.
This will not work with trigger release announcement as it can't
get the version from GITHUB_REF as it isn't available there.
This commit adds the ability to provide an optional environment
variable VERSION to the trigger-release-announcement step. If the
variable is set, the version will be taken from that rather than
trying to parse it out of GITHUB_REF.
Closes #22

Allow for overriding how trigger release announcement step gets version information

---

.release-notes/24.md
README.md
RELEASE_PROCESS.md
action.yml
scripts/announce-a-release.bash
scripts/start-a-release.bash
scripts/trigger-release-announcement.bash

GitHub is in the process of changing the default branch for all
newly created repositories from `master` to `main`. When that happens,
this action will stop working for any new repos unless this change is
made.
With this change, release-bot-action now takes an optional input parameter
`default_branch` that can be used to change what the default branch of the
repo is.
The default branch is the branch that we push back changelog, release note,
and other changes. The default is set to `main` to be forward compatible with
what will become standard on GitHub. Because `main` was chosen as the default,
this is a breaking change.
All repositories still using `master` as the default branch will need to set
the `default_branch` value to `master` to continue working when they upgrade
to a version of …

Allow for setting the default branch

---

.release-notes/28.md
scripts/start-a-release.bash

There's an info.version field in corral.json that should be updated
on release. This change picks up doing that.
Closes #27

Update version in corral.json on release

---

.release-notes/30.md
scripts/start-a-release.bash

The X.Y.Z tag will live on. Use an annotated tag as they can be signed.
From the documentation:
Annotated tags, however, are stored as full objects in the Git database.
They’re checksummed; contain the tagger name, email, and date; have a
tagging message; and can be signed and verified with GNU Privacy Guard
(GPG). It’s generally recommended that you create annotated tags so you
can have all this information; but if you want a temporary tag or for
some reason don’t want to keep the other information, lightweight tags
are available too.

Use annotated tags for releases

---

.release-notes/33.md
Dockerfile
README.md
action.yml
entrypoint.sh
scripts/announce-a-release.bash
scripts/start-a-release.bash
scripts/trigger-release-announcement.bash

GitHub actions already provides a mean to run a specific "subcommand"
via changing the entrypoint. Having a "step" input that operated in the
same way but different from what GitHub actions had built in feels problematic.
This change is a first step towards a rather large redoing of the release-bot-action.

Replace "step" input parameter with overriding of entrypoint

---

.release-notes/34.md
README.md
action.yml
scripts/announce-a-release.bash
scripts/start-a-release.bash
scripts/trigger-release-announcement.bash

When we were supporting v1, we had to take a default branch to push
changes back to as well as jump through hoops with setting up proper
access urls to push to it.
actions/checkout v2 is a lot more featureful. One of those features
is to take a branch (under the input `ref`) to check out as well as
the token to use to checkout.
Switching to v2 and moving the "default branch" and "token to push/pull
GitHub with" into the checkout step from our scripts is an overall win.
This is a breaking change as I don't want to try to figure out supporting
both v1 and v2.
Closes #32

Switch supported actions/checkout from v1 to v2

---

.release-notes/38.md
Dockerfile
Makefile
scripts/update-action-to-use-docker-image-to-run-action.py
scripts/update-action-to-use-dockerfile-to-run-action.py

The best way to run a released GitHub action is to use a prebuilt docker
image. This saves time with building the image and guarantees that each
run will be using exactly the same action code.
This is best accomplished by settings runs.image to the image in question
in action.yml.
However, this does have a drawback of not being able to use arbitrary commits
to run with as that commit will be grabbed BUT... the image in its action.yml
will be used. This is problematic for testing actions.
The two commands included in this commit address both issues.
- update-action-to-use-docker-image-to-run-action.py
Updates runs.image to a docker image with the version we are releasing.
As part of the release process for an action, it should then also make
sure to push a prebuilt image to DockerHub for …

Add command to update the runner in action.yml files

---

scripts/update-version-in-README.py

If the new version was not as long as the old in terms of characters,
it would leave "extra" characters around as we weren't truncating the file
to our new length.

Fix data corruption bug in new readme-version-updater command

---

.github/workflows/release.yml
.release-notes/26.md
README.md
action.yml
scripts/add-unreleased-section-to-changelog.bash
scripts/announce-a-release.bash
scripts/pre-artefact-changelog-check.bash
scripts/trigger-artefact-creation.bash
scripts/trigger-release-announcement.bash
scripts/update-action-to-use-docker-image-to-run-action.py
scripts/update-action-to-use-dockerfile-to-run-action.py
scripts/update-changelog-for-release.bash
scripts/update-version-in-README.py
scripts/update-version-in-VERSION.bash
scripts/update-version-in-corral-json.bash

The preartefact-changelog-check.bash command validates that the changelog
contains an entry for `X.Y.Z` where `X.Y.Z` is the release that is underway.
The command can be used to protect against misconfiguration of workflows and
more importantly, a user inadvertently pushing a `X.Y.Z` tag to start a release
rather than the correct `release-X.Y.Z`.
Closes #26

Add preartefact-changelog-check.bash command

---

.release-notes/ponyc-special-release.md
scripts/trigger-release-announcement

We build ponyc in CirrusCI, not GitHub actions. We do this because we
often need to build LLVM from source and GitHub doesn't provide execution
environments that are powerful enough. This results in a change where we
can't use a stock release-bot `trigger-release-announcement` command.
When the ponyc workflow goes to trigger release announcements, the tag
used to build isn't available so the version needs to be provided via the
`CUSTOM_VERSION` environment variable that is added in this change.
This functionality should have been included in 0.6.0 but was missed.

Add support for ponyc's specialized build requirements

---

Dockerfile

PyGitHub needs the python crypto library and there are no wheels for
that available on Alpine. To use the newer version of PyGitHub, we need
to build the crypto library from source and that now means setting up
rust.
The result... it takes much longer to build from an Alpine base.
Closes #49

Switch Dockerfile to be based on Ubuntu 20.04

---

.release-notes/cranky-git.md
scripts/add-unreleased-section-to-changelog
scripts/delete-announcement-tag
scripts/rotate-release-notes
scripts/trigger-artefact-creation
scripts/trigger-release-announcement
scripts/update-action-to-use-docker-image-to-run-action
scripts/update-action-to-use-dockerfile-to-run-action
scripts/update-changelog-for-release
scripts/update-version-in-README
scripts/update-version-in-VERSION
scripts/update-version-in-corral-json

Newer versions of git have added a check to see if the user running a command
is the same as the user who owns the repository. If they don't match, the
command fails. Adding the repository directory to a "safe list" addresses the
issue.

Update to work with newer versions of git

---

.github/workflows/release.yml
Makefile

We are transitioning from DockerHub to GHCR. While that transition is underway, we are pushing images to both registries.

Push all images to GitHub Container Registry in addition to Docker Hub

---

.release-notes/fix-broken.md
scripts/update-action-to-use-docker-image-to-run-action

It turns out our CI linting would show green for code that had failed linting. That is a bad setup. In the process, the last release had a syntax error in it.
This commit fixes that issue. The pylint problem still needs to be addressed.

Fixed syntax error in `update-action-to-use-docker-image-to-run-action`

---

Makefile

We now stop if any linting fails thereby failing the job if any fail. Previously the exit code for the job would be "0" if the last linting succeeded.
Fixes #65

Fix broken `make pylint`

---

.release-notes/83.md
scripts/publish-release-notes-to-github

Previously, the uploading of release notes assumed that the release didn't exist yet. This made sense for all our ponylang usage. However, for other projects that create assets as part of the build process and store them in GitHub releases rather than Cloudsmith, the release might already exist.
Now, we will check to see if the release exists. If it does, we update it with our release notes. If it doesn't, we will create the release like we previously did.

Handle release already existing when uploading release notes
